// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2JSIrtyAGj0M23XdALk9K6KTTbfFXilE',
    appId: '1:64799472887:android:02d90046e029d5d25ca7f2',
    messagingSenderId: '64799472887',
    projectId: 'clone-olx-a12',
    storageBucket: 'clone-olx-a12.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBV3aA7VM1hg2j5hOqVRjdedPnfd93oOs',
    appId: '1:64799472887:web:1cbe1204bb293eb95ca7f2',
    messagingSenderId: '64799472887',
    projectId: 'clone-olx-a12',
    authDomain: 'clone-olx-a12.firebaseapp.com',
    storageBucket: 'clone-olx-a12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvzFnOaVcU17WVukYLgCxld-7QbJwKwis',
    appId: '1:64799472887:ios:d1910d5f97e6f2765ca7f2',
    messagingSenderId: '64799472887',
    projectId: 'clone-olx-a12',
    storageBucket: 'clone-olx-a12.firebasestorage.app',
    androidClientId: '64799472887-bblrne91bfg91plhvjhk2lsrlacidn5g.apps.googleusercontent.com',
    iosClientId: '64799472887-v19hu8s1f5v3j9hjfrlot436elsdktr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBV3aA7VM1hg2j5hOqVRjdedPnfd93oOs',
    appId: '1:64799472887:web:2c25368621064e715ca7f2',
    messagingSenderId: '64799472887',
    projectId: 'clone-olx-a12',
    authDomain: 'clone-olx-a12.firebaseapp.com',
    storageBucket: 'clone-olx-a12.firebasestorage.app',
  );

}